import Head from 'next/head'
import { useRouter } from 'next/router';
import Layout from '@components/layout'
import AddForm from '@components/AddForm'

export default function FormPage() {
    const router = useRouter();

    if (typeof window !== "undefined") {
        if (!localStorage.getItem("email")) {
            router.push("/")
        }
    }
    return (
        <>
            <Head>
              <title>Добавление товара</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <AddForm/>
            </Layout>
        </>
    )
}
