import Head from 'next/head'
import { useRouter } from 'next/router';
import { LoginModal } from '@components/Modal'

export default function Home() {

    const router = useRouter();

    if (typeof window !== "undefined") {
        if (localStorage.getItem("email")) {
            router.push("/catalog")
        }
    }
    return (
        <>
            <Head>
              <title>Войдите в аккаунт</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <LoginModal />
        </>
    )
}
