import Head from 'next/head'
import { useRouter } from 'next/router';
import Layout from '@components/layout'
import Orders from '@components/Orders';

export async function getStaticProps() {
    const response = await fetch("https://diplom-e-commerce-server.onrender.com/api/auth/orders");

    const data = await response.json();

    return {
        props: {
            orders: data
        },
        revalidate: 20,
    }
}

export default function OrdersPage({ orders }: any) {
    const router = useRouter();

    if (typeof window !== "undefined") {
        if (!localStorage.getItem("email")) {
            router.push("/")
        }
    }

    return (
        <>
            <Head>
              <title>Cтатусы заказов</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Orders orders={orders.orders}/>
            </Layout>
        </>
    )
}